#!/usr/bin/env bash
# Writes the Homebrew formula and Scoop manifest for a release.
#
# Usage: package-manifests.sh TAG CHECKSUMS OUTDIR
#
# TAG is the release tag (v1.2.3), CHECKSUMS the release's checksums.txt, and
# OUTDIR receives Formula/prpr.rb and bucket/prpr.json. REPOSITORY (owner/name)
# selects the download URLs and defaults to DragosMocrii/prpr.
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 TAG CHECKSUMS OUTDIR" >&2
  exit 2
fi
tag=$1
checksums=$2
out=$3
version=${tag#v}
repository=${REPOSITORY:-DragosMocrii/prpr}
homepage="https://github.com/${repository}"
download="${homepage}/releases/download/${tag}"
description="Terminal app for monitoring your open GitHub pull requests and review requests"

# sha prints the checksum of the archive for one platform, or fails.
sha() {
  local file="prpr_${version}_$1"
  local sum
  sum=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1 }' "$checksums")
  if [[ ! "$sum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "no checksum for $file in $checksums" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

darwin_arm64=$(sha darwin_arm64.tar.gz)
darwin_amd64=$(sha darwin_amd64.tar.gz)
linux_arm64=$(sha linux_arm64.tar.gz)
linux_amd64=$(sha linux_amd64.tar.gz)
windows_arm64=$(sha windows_arm64.zip)
windows_amd64=$(sha windows_amd64.zip)

mkdir -p "$out/Formula" "$out/bucket"

cat > "$out/Formula/prpr.rb" <<EOF
# Generated by the prpr release workflow; changes here are overwritten.
class Prpr < Formula
  desc "${description}"
  homepage "${homepage}"
  version "${version}"
  license "MIT"

  depends_on "gh"

  on_macos do
    on_arm do
      url "${download}/prpr_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${download}/prpr_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${download}/prpr_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${download}/prpr_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "prpr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/prpr --version")
  end
end
EOF

cat > "$out/bucket/prpr.json" <<EOF
{
    "version": "${version}",
    "description": "${description}",
    "homepage": "${homepage}",
    "license": "MIT",
    "depends": "gh",
    "architecture": {
        "64bit": {
            "url": "${download}/prpr_${version}_windows_amd64.zip",
            "hash": "${windows_amd64}",
            "extract_dir": "prpr_${version}_windows_amd64"
        },
        "arm64": {
            "url": "${download}/prpr_${version}_windows_arm64.zip",
            "hash": "${windows_arm64}",
            "extract_dir": "prpr_${version}_windows_arm64"
        }
    },
    "bin": "prpr.exe"
}
EOF
